# Generated by Django 5.2.7 on 2025-10-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture (max 5MB, must be an image)",
                null=True,
                upload_to="profile_pictures/%Y/%m/",
            ),
        ),
    ]
