# Generated by Django 5.2.7 on 2025-10-14 12:06

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("skillhub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillfeedback",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rating from 0 to 5",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="rating",
            ),
        ),
    ]
