# Generated by Django 5.2.7 on 2025-10-14 12:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("skillhub", "0002_alter_skillfeedback_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this skill is currently available for teaching",
                verbose_name="active status",
            ),
        ),
    ]
