# Generated by Django 5.2.7 on 2025-10-15 05:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("skillhub", "0003_skill_is_active"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="skillfeedback",
            name="skillhub_sk_user_sk_271034_idx",
        ),
        migrations.AlterUniqueTogether(
            name="skillfeedback",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="skillfeedback",
            name="exchange",
            field=models.OneToOneField(
                default=None,
                help_text="The completed exchange for which feedback is being given",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="skillhub.skillexchange",
                verbose_name="exchange",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="skillfeedback",
            index=models.Index(
                fields=["exchange", "-created_at"],
                name="skillhub_sk_exchang_73be51_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="skillfeedback",
            name="student",
        ),
        migrations.RemoveField(
            model_name="skillfeedback",
            name="user_skill",
        ),
    ]
